# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 01:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.ManyToManyField(related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('clerk', 'Login as a Clerk on POS'),),
            },
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('credits', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[(b'new', b'New'), (b'active', b'Active'), (b'cashout', b'Cash Out'), (b'redeemed', b'Redeemed'), (b'expired', b'Expired')], default=b'new', max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='account.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
