# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontoken',
            name='pin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Pin'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('cashout', 'Cash Out'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], default='new', max_length=20),
        ),
    ]
