# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161213_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL),
        ),
    ]
